
# parameters used in AlphaZero processes
temperature = 1.25
learn_iterations = 100
num_epochs = 4
training_batch_size = 64 
self_play_iterations = 4
num_self_play_batches = 2048 # how many games will be played in parellel in self play

# parameters used in MCTS
iterations = 1000
exploration_const = 2
simulate_round_limit = 400 # 200 per player => 200 rounds/turns
# https://jonathan-laurent.github.io/AlphaZero.jl/stable/reference/params/#AlphaZero.MctsParams
dirichlet_alpha = 0.3
dirichlet_epsilon = 0.25

# parameters used in optimizer
wd = 0.0001
lr = 0.001